""" A quick script which takes the results of the fitting done by PlotBinnedTraining.R 
and outputs the text file parameters as C++ code.

Files from R look like

"","(Intercept)","SNR","I(SNR^2)","I(SNR^3)"
"Dark",8.55651592988201,-1.73677813426316,0.165522479742324,-0.00505567203660016
"Match",7.98341706154684,-0.996487286249378,0.100764178355062,-0.00304942727101111
"Stick",6.12573768546531,-1.47319809845774,0.125843118877494,-0.00326392185432165

"""

import glob
direc = "/Users/nigel/git/cafe-quality/NotTracked/"
fs =  glob.glob(direc+"*.params")

of = open(direc+"Parameters.cpp",'w')



mapLines = []
decLines = ["/* Autogenerated by OutputDiNucleotideContexts.py",
            " * Rows are Dark, Match, Stick (Branch is the reference)",
            " * Columns are Intercept, SNR, SNR^2, SNR^3 */"] 
for f in fs:
    ctx = f.split("/")[-1].split(" ")[0]
    decLines.append("Matrix<double> "+ ctx + " = { ")
    d = [x.strip().split(",")[1:] for x in open(f).readlines()[1:]]
    inside = ",\n".join(["\t{ " + ", ".join(l)+" }" for l in d])
    decLines.append(inside)
    decLines.append("\t};")
    mapLines.append('{"'+ctx+'", &'+ctx+'}')
    #mapLines.append('parameter_store["' + ctx + '"] = '+ ctx+";")
    
of.write("\n".join(decLines))
of.write("\n"*2)
of.write(",".join(mapLines))
of.close()