// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Bio.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Bio.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ParameterNameIndex {
            get {
                return ResourceManager.GetString("ParameterNameIndex", resourceCulture);
            }
        }
        
        internal static string GENBANKPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GENBANKPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string ExpectedBoolToBeTrueOrFalse {
            get {
                return ResourceManager.GetString("ExpectedBoolToBeTrueOrFalse", resourceCulture);
            }
        }
        
        internal static string FirstInputSequenceMismatchSimilarityMatrix {
            get {
                return ResourceManager.GetString("FirstInputSequenceMismatchSimilarityMatrix", resourceCulture);
            }
        }
        
        internal static string RowKeyIndexSeemsToReferToAFileOfTheWrongFormat {
            get {
                return ResourceManager.GetString("RowKeyIndexSeemsToReferToAFileOfTheWrongFormat", resourceCulture);
            }
        }
        
        internal static string ExpectedMaxLengthToGreaterThanOne {
            get {
                return ResourceManager.GetString("ExpectedMaxLengthToGreaterThanOne", resourceCulture);
            }
        }
        
        internal static string DoubleRangeInvalidArgs {
            get {
                return ResourceManager.GetString("DoubleRangeInvalidArgs", resourceCulture);
            }
        }
        
        internal static string SimilarityMatrix_BadOrMissingValue {
            get {
                return ResourceManager.GetString("SimilarityMatrix_BadOrMissingValue", resourceCulture);
            }
        }
        
        internal static string NEWICK_NAME {
            get {
                return ResourceManager.GetString("NEWICK_NAME", resourceCulture);
            }
        }
        
        internal static string NcbiBlastUnknownParam {
            get {
                return ResourceManager.GetString("NcbiBlastUnknownParam", resourceCulture);
            }
        }
        
        internal static string SIMPLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("SIMPLE_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string InvalidSymbol {
            get {
                return ResourceManager.GetString("InvalidSymbol", resourceCulture);
            }
        }
        
        internal static string GAP_COST_NAME {
            get {
                return ResourceManager.GetString("GAP_COST_NAME", resourceCulture);
            }
        }
        
        internal static string FASTQPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FASTQPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string LibraryInvalidParameters {
            get {
                return ResourceManager.GetString("LibraryInvalidParameters", resourceCulture);
            }
        }
        
        internal static string BREAK_LENGTH_DESCRIPTION {
            get {
                return ResourceManager.GetString("BREAK_LENGTH_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string FastQName {
            get {
                return ResourceManager.GetString("FastQName", resourceCulture);
            }
        }
        
        internal static string Ab1InvalidFileSignatureExceptionFormat {
            get {
                return ResourceManager.GetString("Ab1InvalidFileSignatureExceptionFormat", resourceCulture);
            }
        }
        
        internal static string ExpectedArgCountOfThreeOrFour {
            get {
                return ResourceManager.GetString("ExpectedArgCountOfThreeOrFour", resourceCulture);
            }
        }
        
        internal static string ExpectedNonZeroLengthArrayOfMatrices {
            get {
                return ResourceManager.GetString("ExpectedNonZeroLengthArrayOfMatrices", resourceCulture);
            }
        }
        
        internal static string DataParserFactoryNoParserExistsForVersionFormat {
            get {
                return ResourceManager.GetString("DataParserFactoryNoParserExistsForVersionFormat", resourceCulture);
            }
        }
        
        internal static string RefSequenceNofFound {
            get {
                return ResourceManager.GetString("RefSequenceNofFound", resourceCulture);
            }
        }
        
        internal static string ExpectedNoOverlapBetweenRowKeys {
            get {
                return ResourceManager.GetString("ExpectedNoOverlapBetweenRowKeys", resourceCulture);
            }
        }
        
        internal static string ThereAreDuplicateRowsWhichDoNotHDupRowsNonIdenticalValues {
            get {
                return ResourceManager.GetString("ThereAreDuplicateRowsWhichDoNotHDupRowsNonIdenticalValues", resourceCulture);
            }
        }
        
        internal static string MUMLengthTooSmall {
            get {
                return ResourceManager.GetString("MUMLengthTooSmall", resourceCulture);
            }
        }
        
        internal static string SequenceCountMismatch {
            get {
                return ResourceManager.GetString("SequenceCountMismatch", resourceCulture);
            }
        }
        
        internal static string ParameterNameSequences {
            get {
                return ResourceManager.GetString("ParameterNameSequences", resourceCulture);
            }
        }
        
        internal static string GFF_FILEEXTENSION {
            get {
                return ResourceManager.GetString("GFF_FILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string GenbankInvalidFeature {
            get {
                return ResourceManager.GetString("GenbankInvalidFeature", resourceCulture);
            }
        }
        
        internal static string ExpectedByteArrayLengthAndBytesPerValueToBeEqual {
            get {
                return ResourceManager.GetString("ExpectedByteArrayLengthAndBytesPerValueToBeEqual", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionInvalidValueFoundInt {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionInvalidValueFoundInt", resourceCulture);
            }
        }
        
        internal static string BedDesc {
            get {
                return ResourceManager.GetString("BedDesc", resourceCulture);
            }
        }
        
        internal static string ParseHeaderError {
            get {
                return ResourceManager.GetString("ParseHeaderError", resourceCulture);
            }
        }
        
        internal static string InvalidItemSizeExceptionFormat {
            get {
                return ResourceManager.GetString("InvalidItemSizeExceptionFormat", resourceCulture);
            }
        }
        
        internal static string CorruptedDeltaAlignmentFile {
            get {
                return ResourceManager.GetString("CorruptedDeltaAlignmentFile", resourceCulture);
            }
        }
        
        internal static string ErrorConvertingValGaveMissingValue {
            get {
                return ResourceManager.GetString("ErrorConvertingValGaveMissingValue", resourceCulture);
            }
        }
        
        internal static string InvalidStartData {
            get {
                return ResourceManager.GetString("InvalidStartData", resourceCulture);
            }
        }
        
        internal static string IntRangeInvalidArgs {
            get {
                return ResourceManager.GetString("IntRangeInvalidArgs", resourceCulture);
            }
        }
        
        internal static string FIELDPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FIELDPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string ParameterNameValue {
            get {
                return ResourceManager.GetString("ParameterNameValue", resourceCulture);
            }
        }
        
        internal static string SequenceRangeNonNegative {
            get {
                return ResourceManager.GetString("SequenceRangeNonNegative", resourceCulture);
            }
        }
        
        internal static string AmbiguousDnaAlphabetName {
            get {
                return ResourceManager.GetString("AmbiguousDnaAlphabetName", resourceCulture);
            }
        }
        
        internal static string ContigLength {
            get {
                return ResourceManager.GetString("ContigLength", resourceCulture);
            }
        }
        
        internal static string ExpectedMatrixViewColKeysToBeSubsetOfParentMatrix {
            get {
                return ResourceManager.GetString("ExpectedMatrixViewColKeysToBeSubsetOfParentMatrix", resourceCulture);
            }
        }
        
        internal static string QuerySequenceCannotBeNull {
            get {
                return ResourceManager.GetString("QuerySequenceCannotBeNull", resourceCulture);
            }
        }
        
        internal static string ParameterNameSource {
            get {
                return ResourceManager.GetString("ParameterNameSource", resourceCulture);
            }
        }
        
        internal static string NcbiBlastInvalidValue {
            get {
                return ResourceManager.GetString("NcbiBlastInvalidValue", resourceCulture);
            }
        }
        
        internal static string ParameterMustNonNegative {
            get {
                return ResourceManager.GetString("ParameterMustNonNegative", resourceCulture);
            }
        }
        
        internal static string UnambiguousDNAalphabetName {
            get {
                return ResourceManager.GetString("UnambiguousDNAalphabetName", resourceCulture);
            }
        }
        
        internal static string CLUSTALW_FILEEXTENSION {
            get {
                return ResourceManager.GetString("CLUSTALW_FILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string CouldNotIdentifyAlphabetType {
            get {
                return ResourceManager.GetString("CouldNotIdentifyAlphabetType", resourceCulture);
            }
        }
        
        internal static string ComplementNotFound {
            get {
                return ResourceManager.GetString("ComplementNotFound", resourceCulture);
            }
        }
        
        internal static string AccessionSequenceNotFound {
            get {
                return ResourceManager.GetString("AccessionSequenceNotFound", resourceCulture);
            }
        }
        
        internal static string SequenceRangeToStringFormat {
            get {
                return ResourceManager.GetString("SequenceRangeToStringFormat", resourceCulture);
            }
        }
        
        internal static string RnaAlphabetName {
            get {
                return ResourceManager.GetString("RnaAlphabetName", resourceCulture);
            }
        }
        
        internal static string LENGTH_OF_MUM_DESCRIPTION {
            get {
                return ResourceManager.GetString("LENGTH_OF_MUM_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string MUMmerDescription {
            get {
                return ResourceManager.GetString("MUMmerDescription", resourceCulture);
            }
        }
        
        internal static string BREAK_LENGTH_NAME {
            get {
                return ResourceManager.GetString("BREAK_LENGTH_NAME", resourceCulture);
            }
        }
        
        internal static string ExpectedFileToHaveHeader {
            get {
                return ResourceManager.GetString("ExpectedFileToHaveHeader", resourceCulture);
            }
        }
        
        internal static string INVALID_SYMBOL {
            get {
                return ResourceManager.GetString("INVALID_SYMBOL", resourceCulture);
            }
        }
        
        internal static string GENBANK_FILEEXTENSION {
            get {
                return ResourceManager.GetString("GENBANK_FILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string CmdLineParserOptional {
            get {
                return ResourceManager.GetString("CmdLineParserOptional", resourceCulture);
            }
        }
        
        internal static string SimilarityMatrix_InvalidMoleculeType {
            get {
                return ResourceManager.GetString("SimilarityMatrix_InvalidMoleculeType", resourceCulture);
            }
        }
        
        internal static string BAMPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("BAMPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string InvalidPatternMessage {
            get {
                return ResourceManager.GetString("InvalidPatternMessage", resourceCulture);
            }
        }
        
        internal static string SIMILARITY_MATRIX_NAME {
            get {
                return ResourceManager.GetString("SIMILARITY_MATRIX_NAME", resourceCulture);
            }
        }
        
        internal static string IONoTextToParse {
            get {
                return ResourceManager.GetString("IONoTextToParse", resourceCulture);
            }
        }
        
        internal static string StartDataCannotBeNull {
            get {
                return ResourceManager.GetString("StartDataCannotBeNull", resourceCulture);
            }
        }
        
        internal static string InvalidParameter {
            get {
                return ResourceManager.GetString("InvalidParameter", resourceCulture);
            }
        }
        
        internal static string MINIMUM_SCORE_NAME {
            get {
                return ResourceManager.GetString("MINIMUM_SCORE_NAME", resourceCulture);
            }
        }
        
        internal static string ReadCannotBeNull {
            get {
                return ResourceManager.GetString("ReadCannotBeNull", resourceCulture);
            }
        }
        
        internal static string CmdLineParserFirstParam {
            get {
                return ResourceManager.GetString("CmdLineParserFirstParam", resourceCulture);
            }
        }
        
        internal static string SIMILARITY_MATRIX_DESCRIPTION {
            get {
                return ResourceManager.GetString("SIMILARITY_MATRIX_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string MayNotConvert {
            get {
                return ResourceManager.GetString("MayNotConvert", resourceCulture);
            }
        }
        
        internal static string RealAssert {
            get {
                return ResourceManager.GetString("RealAssert", resourceCulture);
            }
        }
        
        internal static string CouldNotRecognizeAlphabet {
            get {
                return ResourceManager.GetString("CouldNotRecognizeAlphabet", resourceCulture);
            }
        }
        
        internal static string SequenceLengthMismatch {
            get {
                return ResourceManager.GetString("SequenceLengthMismatch", resourceCulture);
            }
        }
        
        internal static string InvalidReferredAlphabet {
            get {
                return ResourceManager.GetString("InvalidReferredAlphabet", resourceCulture);
            }
        }
        
        internal static string ExpectedColumnsToMatch {
            get {
                return ResourceManager.GetString("ExpectedColumnsToMatch", resourceCulture);
            }
        }
        
        internal static string MinLengthMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("MinLengthMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionRequiredParameterMissing {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionRequiredParameterMissing", resourceCulture);
            }
        }
        
        internal static string ExpectedColumnKeysCountToEqualValueArrayCount {
            get {
                return ResourceManager.GetString("ExpectedColumnKeysCountToEqualValueArrayCount", resourceCulture);
            }
        }
        
        internal static string OnlyDNAOrRNAInput {
            get {
                return ResourceManager.GetString("OnlyDNAOrRNAInput", resourceCulture);
            }
        }
        
        internal static string NotSupportedReadOnlyCollection {
            get {
                return ResourceManager.GetString("NotSupportedReadOnlyCollection", resourceCulture);
            }
        }
        
        internal static string ExpectedRowKeysCountToEqualValueArrayCount {
            get {
                return ResourceManager.GetString("ExpectedRowKeysCountToEqualValueArrayCount", resourceCulture);
            }
        }
        
        internal static string FileNameMustNotContainPathInformation {
            get {
                return ResourceManager.GetString("FileNameMustNotContainPathInformation", resourceCulture);
            }
        }
        
        internal static string FastQ_InvalidQualityScoreHeaderLine {
            get {
                return ResourceManager.GetString("FastQ_InvalidQualityScoreHeaderLine", resourceCulture);
            }
        }
        
        internal static string ProteinAlphabetName {
            get {
                return ResourceManager.GetString("ProteinAlphabetName", resourceCulture);
            }
        }
        
        internal static string SAM_NO_REFERENCE_DEFINED_INDICATOR {
            get {
                return ResourceManager.GetString("SAM_NO_REFERENCE_DEFINED_INDICATOR", resourceCulture);
            }
        }
        
        internal static string DeltaAlignmentIDDoesnotMatch {
            get {
                return ResourceManager.GetString("DeltaAlignmentIDDoesnotMatch", resourceCulture);
            }
        }
        
        internal static string SAM_FormatMultipleAlignmentsNotSupported {
            get {
                return ResourceManager.GetString("SAM_FormatMultipleAlignmentsNotSupported", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionValueWithoutParameterFound {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionValueWithoutParameterFound", resourceCulture);
            }
        }
        
        internal static string SimilarityMatrix_SecondLineMissing {
            get {
                return ResourceManager.GetString("SimilarityMatrix_SecondLineMissing", resourceCulture);
            }
        }
        
        internal static string LogFileName {
            get {
                return ResourceManager.GetString("LogFileName", resourceCulture);
            }
        }
        
        internal static string MsgPlainOverlapItems {
            get {
                return ResourceManager.GetString("MsgPlainOverlapItems", resourceCulture);
            }
        }
        
        internal static string InvalidSymbolInString {
            get {
                return "Could not recognize one or more symbol in the sequence: {0}";
            }
        }
        
        internal static string KmerLengthShouldBeOver12 {
            get {
                return ResourceManager.GetString("KmerLengthShouldBeOver12", resourceCulture);
            }
        }
        
        internal static string ReverseReadCount {
            get {
                return ResourceManager.GetString("ReverseReadCount", resourceCulture);
            }
        }
        
        internal static string SequenceDataGreaterthan2GB {
            get {
                return ResourceManager.GetString("SequenceDataGreaterthan2GB", resourceCulture);
            }
        }
        
        internal static string Cannotaddmorethanchildnodestoedge {
            get {
                return ResourceManager.GetString("Cannotaddmorethanchildnodestoedge", resourceCulture);
            }
        }
        
        internal static string BlastNoRecords {
            get {
                return ResourceManager.GetString("BlastNoRecords", resourceCulture);
            }
        }
        
        internal static string WiggleName {
            get {
                return ResourceManager.GetString("WiggleName", resourceCulture);
            }
        }
        
        internal static string Ab1ColorDataFromByteArrayEvenNumberRequired {
            get {
                return ResourceManager.GetString("Ab1ColorDataFromByteArrayEvenNumberRequired", resourceCulture);
            }
        }
        
        internal static string GenbankEmptyFeature {
            get {
                return ResourceManager.GetString("GenbankEmptyFeature", resourceCulture);
            }
        }
        
        internal static string PAIRWISE_NAME {
            get {
                return ResourceManager.GetString("PAIRWISE_NAME", resourceCulture);
            }
        }
        
        internal static string OffsetOverflow {
            get {
                return ResourceManager.GetString("OffsetOverflow", resourceCulture);
            }
        }
        
        internal static string XsvSparseParserDesc {
            get {
                return ResourceManager.GetString("XsvSparseParserDesc", resourceCulture);
            }
        }
        
        internal static string KmerPositionOutOfRange {
            get {
                return ResourceManager.GetString("KmerPositionOutOfRange", resourceCulture);
            }
        }
        
        internal static string ParameterShouldBeofType {
            get {
                return ResourceManager.GetString("ParameterShouldBeofType", resourceCulture);
            }
        }
        
        internal static string SequenceAlphabetMismatch {
            get {
                return ResourceManager.GetString("SequenceAlphabetMismatch", resourceCulture);
            }
        }
        
        internal static string SMITH_DESCRIPTION {
            get {
                return ResourceManager.GetString("SMITH_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string PHYLIPPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("PHYLIPPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string FastAContainsMorethanOnebaseAlphabet {
            get {
                return ResourceManager.GetString("FastAContainsMorethanOnebaseAlphabet", resourceCulture);
            }
        }
        
        internal static string InvalidRefNumber {
            get {
                return ResourceManager.GetString("InvalidRefNumber", resourceCulture);
            }
        }
        
        internal static string InvalidRangeMessage {
            get {
                return ResourceManager.GetString("InvalidRangeMessage", resourceCulture);
            }
        }
        
        internal static string ExpectDoubleToBeMinusOneOrOne {
            get {
                return ResourceManager.GetString("ExpectDoubleToBeMinusOneOrOne", resourceCulture);
            }
        }
        
        internal static string ClustalUnknownSequence {
            get {
                return ResourceManager.GetString("ClustalUnknownSequence", resourceCulture);
            }
        }
        
        internal static string DataVirtualizationNeedsInputFile {
            get {
                return ResourceManager.GetString("DataVirtualizationNeedsInputFile", resourceCulture);
            }
        }
        
        internal static string INVALID_INPUT_FILE {
            get {
                return ResourceManager.GetString("INVALID_INPUT_FILE", resourceCulture);
            }
        }
        
        internal static string CmdLineParserException {
            get {
                return ResourceManager.GetString("CmdLineParserException", resourceCulture);
            }
        }
        
        internal static string FastQ_InvalidQualityScoresLength {
            get {
                return ResourceManager.GetString("FastQ_InvalidQualityScoresLength", resourceCulture);
            }
        }
        
        internal static string InvalidSeparator {
            get {
                return ResourceManager.GetString("InvalidSeparator", resourceCulture);
            }
        }
        
        internal static string PoolItemNotContig {
            get {
                return ResourceManager.GetString("PoolItemNotContig", resourceCulture);
            }
        }
        
        internal static string AmbiguousProteinAlphabetName {
            get {
                return ResourceManager.GetString("AmbiguousProteinAlphabetName", resourceCulture);
            }
        }
        
        internal static string SymbolExistsInAlphabet {
            get {
                return ResourceManager.GetString("SymbolExistsInAlphabet", resourceCulture);
            }
        }
        
        internal static string OutOfSpec {
            get {
                return ResourceManager.GetString("OutOfSpec", resourceCulture);
            }
        }
        
        internal static string KurtzSuffixTreeBuilderName {
            get {
                return ResourceManager.GetString("KurtzSuffixTreeBuilderName", resourceCulture);
            }
        }
        
        internal static string ParserPrimaryLineError {
            get {
                return ResourceManager.GetString("ParserPrimaryLineError", resourceCulture);
            }
        }
        
        internal static string DuplicateSQHeader {
            get {
                return ResourceManager.GetString("DuplicateSQHeader", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionRepeatedParameterFoundOnce {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionRepeatedParameterFoundOnce", resourceCulture);
            }
        }
        
        internal static string FileNotOpened {
            get {
                return ResourceManager.GetString("FileNotOpened", resourceCulture);
            }
        }
        
        internal static string UnexpectedSecondSequenceName {
            get {
                return ResourceManager.GetString("UnexpectedSecondSequenceName", resourceCulture);
            }
        }
        
        internal static string BAMFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("BAMFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string NUCMER {
            get {
                return ResourceManager.GetString("NUCMER", resourceCulture);
            }
        }
        
        internal static string ParameterNameStart {
            get {
                return ResourceManager.GetString("ParameterNameStart", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionInvalidValueFound {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionInvalidValueFound", resourceCulture);
            }
        }
        
        internal static string DnaAlphabetName {
            get {
                return ResourceManager.GetString("DnaAlphabetName", resourceCulture);
            }
        }
        
        internal static string SimilarityMatrixCannotBeNull {
            get {
                return ResourceManager.GetString("SimilarityMatrixCannotBeNull", resourceCulture);
            }
        }
        
        internal static string GFFNoFeatures {
            get {
                return ResourceManager.GetString("GFFNoFeatures", resourceCulture);
            }
        }
        
        internal static string BAM_RefSeqNotFound {
            get {
                return ResourceManager.GetString("BAM_RefSeqNotFound", resourceCulture);
            }
        }
        
        internal static string FileAlreadyOpen {
            get {
                return ResourceManager.GetString("FileAlreadyOpen", resourceCulture);
            }
        }
        
        internal static string BAM_InvalidIntValueInOptFieldOfAlignedSeq {
            get {
                return ResourceManager.GetString("BAM_InvalidIntValueInOptFieldOfAlignedSeq", resourceCulture);
            }
        }
        
        internal static string InvalidSearchParameter {
            get {
                return ResourceManager.GetString("InvalidSearchParameter", resourceCulture);
            }
        }
        
        internal static string PARAMETER_VALUE_INVALID {
            get {
                return ResourceManager.GetString("PARAMETER_VALUE_INVALID", resourceCulture);
            }
        }
        
        internal static string BuilderIncorrectLength {
            get {
                return ResourceManager.GetString("BuilderIncorrectLength", resourceCulture);
            }
        }
        
        internal static string InvalidMinLengthOfMatch {
            get {
                return ResourceManager.GetString("InvalidMinLengthOfMatch", resourceCulture);
            }
        }
        
        internal static string SIMPLE_NAME {
            get {
                return ResourceManager.GetString("SIMPLE_NAME", resourceCulture);
            }
        }
        
        internal static string GFFFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GFFFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string ErrorInputDataShouldBeGroupedByVar {
            get {
                return ResourceManager.GetString("ErrorInputDataShouldBeGroupedByVar", resourceCulture);
            }
        }
        
        internal static string BAM_NAME {
            get {
                return ResourceManager.GetString("BAM_NAME", resourceCulture);
            }
        }
        
        internal static string EmptySequence {
            get {
                return ResourceManager.GetString("EmptySequence", resourceCulture);
            }
        }
        
        internal static string ColorDataTrimStartIndexOutOfRange {
            get {
                return ResourceManager.GetString("ColorDataTrimStartIndexOutOfRange", resourceCulture);
            }
        }
        
        internal static string ShouldNotBeSmaller {
            get {
                return ResourceManager.GetString("ShouldNotBeSmaller", resourceCulture);
            }
        }
        
        internal static string ParameterNameInputSequences {
            get {
                return ResourceManager.GetString("ParameterNameInputSequences", resourceCulture);
            }
        }
        
        internal static string AlphabetMisMatch {
            get {
                return ResourceManager.GetString("AlphabetMisMatch", resourceCulture);
            }
        }
        
        internal static string ParameterNameSequence {
            get {
                return ResourceManager.GetString("ParameterNameSequence", resourceCulture);
            }
        }
        
        internal static string ErrorCheckConditionFailed {
            get {
                return ResourceManager.GetString("ErrorCheckConditionFailed", resourceCulture);
            }
        }
        
        internal static string MatchToStringFormat {
            get {
                return ResourceManager.GetString("MatchToStringFormat", resourceCulture);
            }
        }
        
        internal static string SAM_NAME {
            get {
                return ResourceManager.GetString("SAM_NAME", resourceCulture);
            }
        }
        
        internal static string BAM_CantUseBAMIndexStreamDisposed {
            get {
                return ResourceManager.GetString("BAM_CantUseBAMIndexStreamDisposed", resourceCulture);
            }
        }
        
        internal static string CountCannotBeLessThanZero {
            get {
                return ResourceManager.GetString("CountCannotBeLessThanZero", resourceCulture);
            }
        }
        
        internal static string GenBankUnknownLocusFormat {
            get {
                return ResourceManager.GetString("GenBankUnknownLocusFormat", resourceCulture);
            }
        }
        
        internal static string BAM_TextWriterNotSupported {
            get {
                return ResourceManager.GetString("BAM_TextWriterNotSupported", resourceCulture);
            }
        }
        
        internal static string BAM_InvalidOptValType {
            get {
                return ResourceManager.GetString("BAM_InvalidOptValType", resourceCulture);
            }
        }
        
        internal static string ExpectedValToBeSingleCharacter {
            get {
                return ResourceManager.GetString("ExpectedValToBeSingleCharacter", resourceCulture);
            }
        }
        
        internal static string ExpectedOneValueForEveryColKey {
            get {
                return ResourceManager.GetString("ExpectedOneValueForEveryColKey", resourceCulture);
            }
        }
        
        internal static string ExpectedItemToNotExist {
            get {
                return ResourceManager.GetString("ExpectedItemToNotExist", resourceCulture);
            }
        }
        
        internal static string BAM_InvalidEncodedSequenceValue {
            get {
                return ResourceManager.GetString("BAM_InvalidEncodedSequenceValue", resourceCulture);
            }
        }
        
        internal static string SearchParamInvalidArgs {
            get {
                return ResourceManager.GetString("SearchParamInvalidArgs", resourceCulture);
            }
        }
        
        internal static string BAM_FormatStringNotSupported {
            get {
                return ResourceManager.GetString("BAM_FormatStringNotSupported", resourceCulture);
            }
        }
        
        internal static string IOFormatErrorMessage {
            get {
                return ResourceManager.GetString("IOFormatErrorMessage", resourceCulture);
            }
        }
        
        internal static string Parser_InvalidFileFormat {
            get {
                return ResourceManager.GetString("Parser_InvalidFileFormat", resourceCulture);
            }
        }
        
        internal static string FASTA_NAME {
            get {
                return ResourceManager.GetString("FASTA_NAME", resourceCulture);
            }
        }
        
        internal static string APPLIEDBIOSYSTEMS_FILETYPES {
            get {
                return ResourceManager.GetString("APPLIEDBIOSYSTEMS_FILETYPES", resourceCulture);
            }
        }
        
        internal static string ExpectedEveryVarLineToHaveOneTab {
            get {
                return ResourceManager.GetString("ExpectedEveryVarLineToHaveOneTab", resourceCulture);
            }
        }
        
        internal static string WiggleNotSupportedOnVariableStep {
            get {
                return ResourceManager.GetString("WiggleNotSupportedOnVariableStep", resourceCulture);
            }
        }
        
        internal static string PARAMETER_UNKNOWN {
            get {
                return ResourceManager.GetString("PARAMETER_UNKNOWN", resourceCulture);
            }
        }
        
        internal static string ExpectedNonZeroLengthCommentToken {
            get {
                return ResourceManager.GetString("ExpectedNonZeroLengthCommentToken", resourceCulture);
            }
        }
        
        internal static string CouldNotRecognizeSymbol {
            get {
                return ResourceManager.GetString("CouldNotRecognizeSymbol", resourceCulture);
            }
        }
        
        internal static string NEWICK_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("NEWICK_FILE_EXTENSION", resourceCulture);
            }
        }
        
        internal static string ALPHABET_NULL {
            get {
                return ResourceManager.GetString("ALPHABET_NULL", resourceCulture);
            }
        }
        
        internal static string SecondInputSequenceMismatchSimilarityMatrix {
            get {
                return ResourceManager.GetString("SecondInputSequenceMismatchSimilarityMatrix", resourceCulture);
            }
        }
        
        internal static string SAMFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("SAMFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string ErrorNoFilesMatchSpecifiedName {
            get {
                return ResourceManager.GetString("ErrorNoFilesMatchSpecifiedName", resourceCulture);
            }
        }
        
        internal static string CmdLineParserRequired {
            get {
                return ResourceManager.GetString("CmdLineParserRequired", resourceCulture);
            }
        }
        
        internal static string UnknownElement {
            get {
                return ResourceManager.GetString("UnknownElement", resourceCulture);
            }
        }
        
        internal static string XsvSparseFormatterDesc {
            get {
                return ResourceManager.GetString("XsvSparseFormatterDesc", resourceCulture);
            }
        }
        
        internal static string GAP_EXTENSION_COST_DESCRIPTION {
            get {
                return ResourceManager.GetString("GAP_EXTENSION_COST_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string XsvSparseFormatterName {
            get {
                return ResourceManager.GetString("XsvSparseFormatterName", resourceCulture);
            }
        }
        
        internal static string RegistrationLoadingError {
            get {
                return ResourceManager.GetString("RegistrationLoadingError", resourceCulture);
            }
        }
        
        internal static string SegmentByteArrayInvalidCount {
            get {
                return ResourceManager.GetString("SegmentByteArrayInvalidCount", resourceCulture);
            }
        }
        
        internal static string PHYLIP_NAME {
            get {
                return ResourceManager.GetString("PHYLIP_NAME", resourceCulture);
            }
        }
        
        internal static string CmdLineParserRegEx {
            get {
                return ResourceManager.GetString("CmdLineParserRegEx", resourceCulture);
            }
        }
        
        internal static string ExpectedUniqueRowKeysInMatrix {
            get {
                return ResourceManager.GetString("ExpectedUniqueRowKeysInMatrix", resourceCulture);
            }
        }
        
        internal static string SequenceRangeEndError {
            get {
                return ResourceManager.GetString("SequenceRangeEndError", resourceCulture);
            }
        }
        
        internal static string ExpectedHeaderAsFirstLineOfFile {
            get {
                return ResourceManager.GetString("ExpectedHeaderAsFirstLineOfFile", resourceCulture);
            }
        }
        
        internal static string BIOHPC_BLAST_NAME {
            get {
                return ResourceManager.GetString("BIOHPC_BLAST_NAME", resourceCulture);
            }
        }
        
        internal static string MAXIMUM_SEPARATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("MAXIMUM_SEPARATION_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string KmerLengthShouldBePositive {
            get {
                return ResourceManager.GetString("KmerLengthShouldBePositive", resourceCulture);
            }
        }
        
        internal static string ForwardReadCount {
            get {
                return ResourceManager.GetString("ForwardReadCount", resourceCulture);
            }
        }
        
        internal static string FastQ_InvalidQualityScoreHeaderData {
            get {
                return ResourceManager.GetString("FastQ_InvalidQualityScoreHeaderData", resourceCulture);
            }
        }
        
        internal static string ExpectedArguments {
            get {
                return ResourceManager.GetString("ExpectedArguments", resourceCulture);
            }
        }
        
        internal static string FASTQFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FASTQFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string ConditionFailed {
            get {
                return ResourceManager.GetString("ConditionFailed", resourceCulture);
            }
        }
        
        internal static string QualitativeSequenceToStringFormatForLongSequence {
            get {
                return ResourceManager.GetString("QualitativeSequenceToStringFormatForLongSequence", resourceCulture);
            }
        }
        
        internal static string ParameterNameArray {
            get {
                return ResourceManager.GetString("ParameterNameArray", resourceCulture);
            }
        }
        
        internal static string BedFileFormats {
            get {
                return ResourceManager.GetString("BedFileFormats", resourceCulture);
            }
        }
        
        internal static string ColorDataTrimLengthArgumentException {
            get {
                return ResourceManager.GetString("ColorDataTrimLengthArgumentException", resourceCulture);
            }
        }
        
        internal static string Wiggle_FileExtension {
            get {
                return ResourceManager.GetString("Wiggle_FileExtension", resourceCulture);
            }
        }
        
        internal static string BAM_FILEEXTENSION {
            get {
                return ResourceManager.GetString("BAM_FILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string PoolItemNotSequence {
            get {
                return ResourceManager.GetString("PoolItemNotSequence", resourceCulture);
            }
        }
        
        internal static string ParameterMustLessThanCount {
            get {
                return ResourceManager.GetString("ParameterMustLessThanCount", resourceCulture);
            }
        }
        
        internal static string SimilarityMatrix_FewerMatrixLines {
            get {
                return ResourceManager.GetString("SimilarityMatrix_FewerMatrixLines", resourceCulture);
            }
        }
        
        internal static string ParameterNameQuery {
            get {
                return ResourceManager.GetString("ParameterNameQuery", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionSyntaxError2 {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionSyntaxError2", resourceCulture);
            }
        }
        
        internal static string OnlySequenceClassSupported {
            get {
                return ResourceManager.GetString("OnlySequenceClassSupported", resourceCulture);
            }
        }
        
        internal static string GENBANKFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GENBANKFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string StartCannotBeLessThanZero {
            get {
                return ResourceManager.GetString("StartCannotBeLessThanZero", resourceCulture);
            }
        }
        
        internal static string InvalidRangeSizeOfRangeMustBeLessThanMaxValue {
            get {
                return ResourceManager.GetString("InvalidRangeSizeOfRangeMustBeLessThanMaxValue", resourceCulture);
            }
        }
        
        internal static string CmdLineParserString {
            get {
                return ResourceManager.GetString("CmdLineParserString", resourceCulture);
            }
        }
        
        internal static string ErrorConvertingCharacterNucleotideToDouble {
            get {
                return ResourceManager.GetString("ErrorConvertingCharacterNucleotideToDouble", resourceCulture);
            }
        }
        
        internal static string FastQ_NotAQualitativeSequence {
            get {
                return ResourceManager.GetString("FastQ_NotAQualitativeSequence", resourceCulture);
            }
        }
        
        internal static string MUMmerName {
            get {
                return ResourceManager.GetString("MUMmerName", resourceCulture);
            }
        }
        
        internal static string RepeatedFlags {
            get {
                return ResourceManager.GetString("RepeatedFlags", resourceCulture);
            }
        }
        
        internal static string NEXUSPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("NEXUSPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionRequiredFirstParameterMissing {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionRequiredFirstParameterMissing", resourceCulture);
            }
        }
        
        internal static string FIXED_SEPARATION_DESCRIPTION {
            get {
                return ResourceManager.GetString("FIXED_SEPARATION_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string ParameterNameWriter {
            get {
                return ResourceManager.GetString("ParameterNameWriter", resourceCulture);
            }
        }
        
        internal static string CmdLineParserUsage {
            get {
                return ResourceManager.GetString("CmdLineParserUsage", resourceCulture);
            }
        }
        
        internal static string WiggleParserDescription {
            get {
                return ResourceManager.GetString("WiggleParserDescription", resourceCulture);
            }
        }
        
        internal static string CLUSTALWPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("CLUSTALWPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string CmdLineParserParameters {
            get {
                return ResourceManager.GetString("CmdLineParserParameters", resourceCulture);
            }
        }
        
        internal static string MandatoryTagNotFound {
            get {
                return ResourceManager.GetString("MandatoryTagNotFound", resourceCulture);
            }
        }
        
        internal static string TracebackBadSource {
            get {
                return ResourceManager.GetString("TracebackBadSource", resourceCulture);
            }
        }
        
        internal static string QualitativeSequenceToStringFormatForSmallSequence {
            get {
                return ResourceManager.GetString("QualitativeSequenceToStringFormatForSmallSequence", resourceCulture);
            }
        }
        
        internal static string Parser_NoTextErrorMessage {
            get {
                return ResourceManager.GetString("Parser_NoTextErrorMessage", resourceCulture);
            }
        }
        
        internal static string FastQ_InvalidSequenceLine {
            get {
                return ResourceManager.GetString("FastQ_InvalidSequenceLine", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionInvalidValueFoundString {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionInvalidValueFoundString", resourceCulture);
            }
        }
        
        internal static string InvalidQualityScoreFound {
            get {
                return ResourceManager.GetString("InvalidQualityScoreFound", resourceCulture);
            }
        }
        
        internal static string APPLIEDBIOSYSTEMS_NAME {
            get {
                return ResourceManager.GetString("APPLIEDBIOSYSTEMS_NAME", resourceCulture);
            }
        }
        
        internal static string OffsetInvalid {
            get {
                return ResourceManager.GetString("OffsetInvalid", resourceCulture);
            }
        }
        
        internal static string SAMParserAlphabetCantBeSet {
            get {
                return ResourceManager.GetString("SAMParserAlphabetCantBeSet", resourceCulture);
            }
        }
        
        internal static string InvalidRangeSizeOfRangeMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("InvalidRangeSizeOfRangeMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        internal static string ExpectedNoCommentsInRowKeysAnsiFiles {
            get {
                return ResourceManager.GetString("ExpectedNoCommentsInRowKeysAnsiFiles", resourceCulture);
            }
        }
        
        internal static string ParserUnexpectedLineInSequence {
            get {
                return ResourceManager.GetString("ParserUnexpectedLineInSequence", resourceCulture);
            }
        }
        
        internal static string GenBankFailedToParseLocusTokenFormat {
            get {
                return ResourceManager.GetString("GenBankFailedToParseLocusTokenFormat", resourceCulture);
            }
        }
        
        internal static string BAM_TextreaderNotSupportedMessage {
            get {
                return ResourceManager.GetString("BAM_TextreaderNotSupportedMessage", resourceCulture);
            }
        }
        
        internal static string ParameterNameLocation {
            get {
                return ResourceManager.GetString("ParameterNameLocation", resourceCulture);
            }
        }
        
        internal static string ParserInvalidDate {
            get {
                return ResourceManager.GetString("ParserInvalidDate", resourceCulture);
            }
        }
        
        internal static string XsvSparseParserFileTypes {
            get {
                return ResourceManager.GetString("XsvSparseParserFileTypes", resourceCulture);
            }
        }
        
        internal static string AZURE_BLAST_NAME {
            get {
                return ResourceManager.GetString("AZURE_BLAST_NAME", resourceCulture);
            }
        }
        
        internal static string SAM_AlignedSequenceHeaderMissing {
            get {
                return ResourceManager.GetString("SAM_AlignedSequenceHeaderMissing", resourceCulture);
            }
        }
        
        internal static string BedName {
            get {
                return ResourceManager.GetString("BedName", resourceCulture);
            }
        }
        
        internal static string BAM_UnableToReadCompressedBlock {
            get {
                return ResourceManager.GetString("BAM_UnableToReadCompressedBlock", resourceCulture);
            }
        }
        
        internal static string LIST_EMPTY {
            get {
                return ResourceManager.GetString("LIST_EMPTY", resourceCulture);
            }
        }
        
        internal static string ParameterNameSequenceItems {
            get {
                return ResourceManager.GetString("ParameterNameSequenceItems", resourceCulture);
            }
        }
        
        internal static string GffInvalidSequence {
            get {
                return ResourceManager.GetString("GffInvalidSequence", resourceCulture);
            }
        }
        
        internal static string ClusterToStringFormat {
            get {
                return ResourceManager.GetString("ClusterToStringFormat", resourceCulture);
            }
        }
        
        internal static string SIMPLE_SNP_NAME {
            get {
                return ResourceManager.GetString("SIMPLE_SNP_NAME", resourceCulture);
            }
        }
        
        internal static string XsvOffsetNotFound {
            get {
                return ResourceManager.GetString("XsvOffsetNotFound", resourceCulture);
            }
        }
        
        internal static string GffInvalidField {
            get {
                return ResourceManager.GetString("GffInvalidField", resourceCulture);
            }
        }
        
        internal static string ExpectedItemToExist {
            get {
                return ResourceManager.GetString("ExpectedItemToExist", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionRequiredParameterMissing2 {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionRequiredParameterMissing2", resourceCulture);
            }
        }
        
        internal static string QueryListCannotBeNull {
            get {
                return ResourceManager.GetString("QueryListCannotBeNull", resourceCulture);
            }
        }
        
        internal static string ExpectedFileToHaveData {
            get {
                return ResourceManager.GetString("ExpectedFileToHaveData", resourceCulture);
            }
        }
        
        internal static string READ_ONLY_COLLECTION_MESSAGE {
            get {
                return ResourceManager.GetString("READ_ONLY_COLLECTION_MESSAGE", resourceCulture);
            }
        }
        
        internal static string InvalidAlphabetType {
            get {
                return ResourceManager.GetString("InvalidAlphabetType", resourceCulture);
            }
        }
        
        internal static string ExpectedRowsOfMatricesToMatch {
            get {
                return ResourceManager.GetString("ExpectedRowsOfMatricesToMatch", resourceCulture);
            }
        }
        
        internal static string CmdLineParserInt {
            get {
                return ResourceManager.GetString("CmdLineParserInt", resourceCulture);
            }
        }
        
        internal static string InvalidEndData {
            get {
                return ResourceManager.GetString("InvalidEndData", resourceCulture);
            }
        }
        
        internal static string ExpectedAllMatricesToHaveSameMissingValue {
            get {
                return ResourceManager.GetString("ExpectedAllMatricesToHaveSameMissingValue", resourceCulture);
            }
        }
        
        internal static string SEPARATION_FACTOR_NAME {
            get {
                return ResourceManager.GetString("SEPARATION_FACTOR_NAME", resourceCulture);
            }
        }
        
        internal static string WiggleInvalidHeader {
            get {
                return ResourceManager.GetString("WiggleInvalidHeader", resourceCulture);
            }
        }
        
        internal static string InvalidLocationString {
            get {
                return ResourceManager.GetString("InvalidLocationString", resourceCulture);
            }
        }
        
        internal static string NotSupportedInVirtualSequence {
            get {
                return ResourceManager.GetString("NotSupportedInVirtualSequence", resourceCulture);
            }
        }
        
        internal static string GENBANK_NAME {
            get {
                return ResourceManager.GetString("GENBANK_NAME", resourceCulture);
            }
        }
        
        internal static string EBIWUBLAST_NAME {
            get {
                return ResourceManager.GetString("EBIWUBLAST_NAME", resourceCulture);
            }
        }
        
        internal static string AlignedSequenceCount {
            get {
                return ResourceManager.GetString("AlignedSequenceCount", resourceCulture);
            }
        }
        
        internal static string NEWICK_PARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("NEWICK_PARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string InvalidQNameLength {
            get {
                return ResourceManager.GetString("InvalidQNameLength", resourceCulture);
            }
        }
        
        internal static string ExpectedToReadAllBytesOfValue {
            get {
                return ResourceManager.GetString("ExpectedToReadAllBytesOfValue", resourceCulture);
            }
        }
        
        internal static string FIXED_SEPARATION_NAME {
            get {
                return ResourceManager.GetString("FIXED_SEPARATION_NAME", resourceCulture);
            }
        }
        
        internal static string MinimumTwoSequences {
            get {
                return ResourceManager.GetString("MinimumTwoSequences", resourceCulture);
            }
        }
        
        internal static string SMITH_NAME {
            get {
                return ResourceManager.GetString("SMITH_NAME", resourceCulture);
            }
        }
        
        internal static string ExpectToReadRowKey {
            get {
                return ResourceManager.GetString("ExpectToReadRowKey", resourceCulture);
            }
        }
        
        internal static string FileNotClosed {
            get {
                return ResourceManager.GetString("FileNotClosed", resourceCulture);
            }
        }
        
        internal static string LibraryExist {
            get {
                return ResourceManager.GetString("LibraryExist", resourceCulture);
            }
        }
        
        internal static string BAMFormatterSupportsDNAOnly {
            get {
                return ResourceManager.GetString("BAMFormatterSupportsDNAOnly", resourceCulture);
            }
        }
        
        internal static string SAMPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("SAMPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string InvalidQualityScore {
            get {
                return ResourceManager.GetString("InvalidQualityScore", resourceCulture);
            }
        }
        
        internal static string SIMPLE_SNP_DESCRIPTION {
            get {
                return ResourceManager.GetString("SIMPLE_SNP_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string KmerLengthIsTooLong {
            get {
                return ResourceManager.GetString("KmerLengthIsTooLong", resourceCulture);
            }
        }
        
        internal static string ExpectedValToContainTwoCharacters {
            get {
                return ResourceManager.GetString("ExpectedValToContainTwoCharacters", resourceCulture);
            }
        }
        
        internal static string DuplicatingReadIds {
            get {
                return ResourceManager.GetString("DuplicatingReadIds", resourceCulture);
            }
        }
        
        internal static string NEEDLEMAN_NAME {
            get {
                return ResourceManager.GetString("NEEDLEMAN_NAME", resourceCulture);
            }
        }
        
        internal static string ComplementNotSupportedByalphabet {
            get {
                return ResourceManager.GetString("ComplementNotSupportedByalphabet", resourceCulture);
            }
        }
        
        internal static string SimilarityMatrix_NameMissing {
            get {
                return ResourceManager.GetString("SimilarityMatrix_NameMissing", resourceCulture);
            }
        }
        
        internal static string NEEDLEMAN_DESCRIPTION {
            get {
                return ResourceManager.GetString("NEEDLEMAN_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string MatchExtensionToStringFormat {
            get {
                return ResourceManager.GetString("MatchExtensionToStringFormat", resourceCulture);
            }
        }
        
        internal static string MUMmerAlignerName {
            get {
                return ResourceManager.GetString("MUMmerAlignerName", resourceCulture);
            }
        }
        
        internal static string NullLocationBuild {
            get {
                return ResourceManager.GetString("NullLocationBuild", resourceCulture);
            }
        }
        
        internal static string ExpectRowKeyFileAndMainFileToAgreeOnTheRowkeys {
            get {
                return ResourceManager.GetString("ExpectRowKeyFileAndMainFileToAgreeOnTheRowkeys", resourceCulture);
            }
        }
        
        internal static string Expected_var_AsFirstColumnOfHeader {
            get {
                return ResourceManager.GetString("Expected_var_AsFirstColumnOfHeader", resourceCulture);
            }
        }
        
        internal static string ParamCHmustbeLessThan256 {
            get {
                return ResourceManager.GetString("ParamCHmustbeLessThan256", resourceCulture);
            }
        }
        
        internal static string SequenceRangeStartError {
            get {
                return ResourceManager.GetString("SequenceRangeStartError", resourceCulture);
            }
        }
        
        internal static string ParameterNameStartPos {
            get {
                return ResourceManager.GetString("ParameterNameStartPos", resourceCulture);
            }
        }
        
        internal static string InvalidQueryDirection {
            get {
                return ResourceManager.GetString("InvalidQueryDirection", resourceCulture);
            }
        }
        
        internal static string ReferenceListCannotBeNull {
            get {
                return ResourceManager.GetString("ReferenceListCannotBeNull", resourceCulture);
            }
        }
        
        internal static string InvalidRangeBeginMustBeLessThanLast {
            get {
                return ResourceManager.GetString("InvalidRangeBeginMustBeLessThanLast", resourceCulture);
            }
        }
        
        internal static string ExpectedEveryColumnToBeUsedOnceInThePermuation {
            get {
                return ResourceManager.GetString("ExpectedEveryColumnToBeUsedOnceInThePermuation", resourceCulture);
            }
        }
        
        internal static string ExpectedStoreListCountToEqualColCount {
            get {
                return ResourceManager.GetString("ExpectedStoreListCountToEqualColCount", resourceCulture);
            }
        }
        
        internal static string FastQ_EmptyQualityScoreLine {
            get {
                return ResourceManager.GetString("FastQ_EmptyQualityScoreLine", resourceCulture);
            }
        }
        
        internal static string ParameterNameEndPos {
            get {
                return ResourceManager.GetString("ParameterNameEndPos", resourceCulture);
            }
        }
        
        internal static string MsgComplementOverlapItems {
            get {
                return ResourceManager.GetString("MsgComplementOverlapItems", resourceCulture);
            }
        }
        
        internal static string BAM_InvalidIntValueInOptField {
            get {
                return ResourceManager.GetString("BAM_InvalidIntValueInOptField", resourceCulture);
            }
        }
        
        internal static string FastAName {
            get {
                return ResourceManager.GetString("FastAName", resourceCulture);
            }
        }
        
        internal static string SequenceCannotBeNull {
            get {
                return ResourceManager.GetString("SequenceCannotBeNull", resourceCulture);
            }
        }
        
        internal static string ExpectedValidRangeString {
            get {
                return ResourceManager.GetString("ExpectedValidRangeString", resourceCulture);
            }
        }
        
        internal static string BAM_InvalidCIGAR {
            get {
                return ResourceManager.GetString("BAM_InvalidCIGAR", resourceCulture);
            }
        }
        
        internal static string UnknownOption {
            get {
                return ResourceManager.GetString("UnknownOption", resourceCulture);
            }
        }
        
        internal static string ErrorCheckConditionFirstAndOnlyTooFew {
            get {
                return ResourceManager.GetString("ErrorCheckConditionFirstAndOnlyTooFew", resourceCulture);
            }
        }
        
        internal static string GffUnsupportedVersion {
            get {
                return ResourceManager.GetString("GffUnsupportedVersion", resourceCulture);
            }
        }
        
        internal static string NoneWithSubLocs {
            get {
                return ResourceManager.GetString("NoneWithSubLocs", resourceCulture);
            }
        }
        
        internal static string UnbalancedParanthesis {
            get {
                return ResourceManager.GetString("UnbalancedParanthesis", resourceCulture);
            }
        }
        
        internal static string ExpectedRowKeyAndColKeyToBeInMatrix {
            get {
                return ResourceManager.GetString("ExpectedRowKeyAndColKeyToBeInMatrix", resourceCulture);
            }
        }
        
        internal static string SQHeaderMissing {
            get {
                return ResourceManager.GetString("SQHeaderMissing", resourceCulture);
            }
        }
        
        internal static string MAXIMUM_SEPARATION_NAME {
            get {
                return ResourceManager.GetString("MAXIMUM_SEPARATION_NAME", resourceCulture);
            }
        }
        
        internal static string Ab1InvalidFileVersionExceptionFormat {
            get {
                return ResourceManager.GetString("Ab1InvalidFileVersionExceptionFormat", resourceCulture);
            }
        }
        
        internal static string ParserInvalidSourceField {
            get {
                return ResourceManager.GetString("ParserInvalidSourceField", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionUnknownParameterFound2 {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionUnknownParameterFound2", resourceCulture);
            }
        }
        
        internal static string ParameterNameSequenceAlignment {
            get {
                return ResourceManager.GetString("ParameterNameSequenceAlignment", resourceCulture);
            }
        }
        
        internal static string BatchCountCondition {
            get {
                return ResourceManager.GetString("BatchCountCondition", resourceCulture);
            }
        }
        
        internal static string MUMmerAlignerDescription {
            get {
                return ResourceManager.GetString("MUMmerAlignerDescription", resourceCulture);
            }
        }
        
        internal static string BAM_InvalidBAMFile {
            get {
                return ResourceManager.GetString("BAM_InvalidBAMFile", resourceCulture);
            }
        }
        
        internal static string ErrorCheckConditionFirstAndOnlyTooMany {
            get {
                return ResourceManager.GetString("ErrorCheckConditionFirstAndOnlyTooMany", resourceCulture);
            }
        }
        
        internal static string GFF_NAME {
            get {
                return ResourceManager.GetString("GFF_NAME", resourceCulture);
            }
        }
        
        internal static string DestArrayNotLargeEnough {
            get {
                return ResourceManager.GetString("DestArrayNotLargeEnough", resourceCulture);
            }
        }
        
        internal static string SimilarityMatrix_DiagonalSM {
            get {
                return ResourceManager.GetString("SimilarityMatrix_DiagonalSM", resourceCulture);
            }
        }
        
        internal static string RangeCollectionIsEmpty {
            get {
                return ResourceManager.GetString("RangeCollectionIsEmpty", resourceCulture);
            }
        }
        
        internal static string ExpectedTwoFieldsFoundN {
            get {
                return ResourceManager.GetString("ExpectedTwoFieldsFoundN", resourceCulture);
            }
        }
        
        internal static string InvalidType {
            get {
                return ResourceManager.GetString("InvalidType", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionInvalidValueFoundInts {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionInvalidValueFoundInts", resourceCulture);
            }
        }
        
        internal static string DensePairAnsiMissingValueSignatureMustBe {
            get {
                return ResourceManager.GetString("DensePairAnsiMissingValueSignatureMustBe", resourceCulture);
            }
        }
        
        internal static string KmerIndexOutOfRange {
            get {
                return ResourceManager.GetString("KmerIndexOutOfRange", resourceCulture);
            }
        }
        
        internal static string ExpectedCharToBeZeroOrOne {
            get {
                return ResourceManager.GetString("ExpectedCharToBeZeroOrOne", resourceCulture);
            }
        }
        
        internal static string GFFPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("GFFPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string PHYLIP_FILEEXTENSION {
            get {
                return ResourceManager.GetString("PHYLIP_FILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string ParserSecondLocus {
            get {
                return ResourceManager.GetString("ParserSecondLocus", resourceCulture);
            }
        }
        
        internal static string SAM_FILEEXTENSION {
            get {
                return ResourceManager.GetString("SAM_FILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string LENGTH_OF_MUM_NAME {
            get {
                return ResourceManager.GetString("LENGTH_OF_MUM_NAME", resourceCulture);
            }
        }
        
        internal static string ErrorConvertingSparseValToStore {
            get {
                return ResourceManager.GetString("ErrorConvertingSparseValToStore", resourceCulture);
            }
        }
        
        internal static string XsvSparseParserName {
            get {
                return ResourceManager.GetString("XsvSparseParserName", resourceCulture);
            }
        }
        
        internal static string ExpectEachDataRowToHaveNCharacters {
            get {
                return ResourceManager.GetString("ExpectEachDataRowToHaveNCharacters", resourceCulture);
            }
        }
        
        internal static string InputSequenceMustBeGreaterThanMUM {
            get {
                return ResourceManager.GetString("InputSequenceMustBeGreaterThanMUM", resourceCulture);
            }
        }
        
        internal static string NullResolver {
            get {
                return ResourceManager.GetString("NullResolver", resourceCulture);
            }
        }
        
        internal static string NUCMERDESC {
            get {
                return ResourceManager.GetString("NUCMERDESC", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionValueWithoutParameterFound2 {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionValueWithoutParameterFound2", resourceCulture);
            }
        }
        
        internal static string NtaxMismatch {
            get {
                return ResourceManager.GetString("NtaxMismatch", resourceCulture);
            }
        }
        
        internal static string APPLIEDBIOSYSTEMS_DESCRIPTION {
            get {
                return ResourceManager.GetString("APPLIEDBIOSYSTEMS_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string ExpectedThreeFields {
            get {
                return ResourceManager.GetString("ExpectedThreeFields", resourceCulture);
            }
        }
        
        internal static string BAM_FormatMultipleAlignmentsNotSupported {
            get {
                return ResourceManager.GetString("BAM_FormatMultipleAlignmentsNotSupported", resourceCulture);
            }
        }
        
        internal static string NEXUS_FILEEXTENSION {
            get {
                return ResourceManager.GetString("NEXUS_FILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string GAP_EXTENSION_COST_NAME {
            get {
                return ResourceManager.GetString("GAP_EXTENSION_COST_NAME", resourceCulture);
            }
        }
        
        internal static string BAMParserAlphabetCantBeSet {
            get {
                return ResourceManager.GetString("BAMParserAlphabetCantBeSet", resourceCulture);
            }
        }
        
        internal static string DeltaCollectionFileCorrupted {
            get {
                return ResourceManager.GetString("DeltaCollectionFileCorrupted", resourceCulture);
            }
        }
        
        internal static string ExpectedHeaderToBe_var_cid_val {
            get {
                return ResourceManager.GetString("ExpectedHeaderToBe_var_cid_val", resourceCulture);
            }
        }
        
        internal static string BAM_InvalidIndexFile {
            get {
                return ResourceManager.GetString("BAM_InvalidIndexFile", resourceCulture);
            }
        }
        
        internal static string ExpectFileToEndAfterLastValue {
            get {
                return ResourceManager.GetString("ExpectFileToEndAfterLastValue", resourceCulture);
            }
        }
        
        internal static string snpTextReaderNull {
            get {
                return ResourceManager.GetString("snpTextReaderNull", resourceCulture);
            }
        }
        
        internal static string MatePairToStringFormat {
            get {
                return ResourceManager.GetString("MatePairToStringFormat", resourceCulture);
            }
        }
        
        internal static string ReferenceSequenceCannotBeNull {
            get {
                return ResourceManager.GetString("ReferenceSequenceCannotBeNull", resourceCulture);
            }
        }
        
        internal static string ParsingError {
            get {
                return ResourceManager.GetString("ParsingError", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionInvalidValueFoundBool {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionInvalidValueFoundBool", resourceCulture);
            }
        }
        
        internal static string GZIPPED_FILE_EXTENSION {
            get {
                return ResourceManager.GetString("GZIPPED_FILE_EXTENSION", resourceCulture);
            }
        }
        
        internal static string SymbolCountZero {
            get {
                return ResourceManager.GetString("SymbolCountZero", resourceCulture);
            }
        }
        
        internal static string WiggleBadInputInFile {
            get {
                return ResourceManager.GetString("WiggleBadInputInFile", resourceCulture);
            }
        }
        
        internal static string SEPARATION_FACTOR_DESCRIPTION {
            get {
                return ResourceManager.GetString("SEPARATION_FACTOR_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string FIELDPARSER_NAME {
            get {
                return ResourceManager.GetString("FIELDPARSER_NAME", resourceCulture);
            }
        }
        
        internal static string MINIMUM_SCORE_DESCRIPTION {
            get {
                return ResourceManager.GetString("MINIMUM_SCORE_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string HeaderContainsNullValue {
            get {
                return ResourceManager.GetString("HeaderContainsNullValue", resourceCulture);
            }
        }
        
        internal static string BAM_BAMFileNIndexFileContbeSame {
            get {
                return ResourceManager.GetString("BAM_BAMFileNIndexFileContbeSame", resourceCulture);
            }
        }
        
        internal static string CLUSTALW_NAME {
            get {
                return ResourceManager.GetString("CLUSTALW_NAME", resourceCulture);
            }
        }
        
        internal static string AmbiguousRnaAlphabetName {
            get {
                return ResourceManager.GetString("AmbiguousRnaAlphabetName", resourceCulture);
            }
        }
        
        internal static string SAM_InvalidInputFile {
            get {
                return ResourceManager.GetString("SAM_InvalidInputFile", resourceCulture);
            }
        }
        
        internal static string InvalidStartNEndPositions {
            get {
                return ResourceManager.GetString("InvalidStartNEndPositions", resourceCulture);
            }
        }
        
        internal static string NEXUS_NAME {
            get {
                return ResourceManager.GetString("NEXUS_NAME", resourceCulture);
            }
        }
        
        internal static string InvalidRNASequenceInput {
            get {
                return ResourceManager.GetString("InvalidRNASequenceInput", resourceCulture);
            }
        }
        
        internal static string ExpectedEveryColumnToBeAMemberOfThePermutation {
            get {
                return ResourceManager.GetString("ExpectedEveryColumnToBeAMemberOfThePermutation", resourceCulture);
            }
        }
        
        internal static string ProgressStatus_Reading {
            get {
                return ResourceManager.GetString("ProgressStatus_Reading", resourceCulture);
            }
        }
        
        internal static string ComplementWithMorethanOneSubLocs {
            get {
                return ResourceManager.GetString("ComplementWithMorethanOneSubLocs", resourceCulture);
            }
        }
        
        internal static string DifferenceInSequenceAndQualityScoresLengthMessage {
            get {
                return ResourceManager.GetString("DifferenceInSequenceAndQualityScoresLengthMessage", resourceCulture);
            }
        }
        
        internal static string SequenceLengthExceedsLimit {
            get {
                return ResourceManager.GetString("SequenceLengthExceedsLimit", resourceCulture);
            }
        }
        
        internal static string EndDataCannotBeNull {
            get {
                return ResourceManager.GetString("EndDataCannotBeNull", resourceCulture);
            }
        }
        
        internal static string MsgReverseOverlapItems {
            get {
                return ResourceManager.GetString("MsgReverseOverlapItems", resourceCulture);
            }
        }
        
        internal static string SAMFormatterSupportsDNAOnly {
            get {
                return ResourceManager.GetString("SAMFormatterSupportsDNAOnly", resourceCulture);
            }
        }
        
        internal static string OnlyAmbiguousRnaCanContainAmbiguousSymbolsOnTranslation {
            get {
                return ResourceManager.GetString("OnlyAmbiguousRnaCanContainAmbiguousSymbolsOnTranslation", resourceCulture);
            }
        }
        
        internal static string ExpectedUoPairElementsToBeIComparable {
            get {
                return ResourceManager.GetString("ExpectedUoPairElementsToBeIComparable", resourceCulture);
            }
        }
        
        internal static string SequenceLengthsMismatch {
            get {
                return ResourceManager.GetString("SequenceLengthsMismatch", resourceCulture);
            }
        }
        
        internal static string SAMAlignmentHeaderNotFound {
            get {
                return ResourceManager.GetString("SAMAlignmentHeaderNotFound", resourceCulture);
            }
        }
        
        internal static string MultiWaySuffixTreeName {
            get {
                return ResourceManager.GetString("MultiWaySuffixTreeName", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionSyntaxError3 {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionSyntaxError3", resourceCulture);
            }
        }
        
        internal static string InputAlphabetsMismatch {
            get {
                return ResourceManager.GetString("InputAlphabetsMismatch", resourceCulture);
            }
        }
        
        internal static string KmerLengthGreaterThan31 {
            get {
                return ResourceManager.GetString("KmerLengthGreaterThan31", resourceCulture);
            }
        }
        
        internal static string WiggleFormatterDescription {
            get {
                return ResourceManager.GetString("WiggleFormatterDescription", resourceCulture);
            }
        }
        
        internal static string ParameterNameSize {
            get {
                return ResourceManager.GetString("ParameterNameSize", resourceCulture);
            }
        }
        
        internal static string SAMAlignedSequenceHeaderNotFound {
            get {
                return ResourceManager.GetString("SAMAlignedSequenceHeaderNotFound", resourceCulture);
            }
        }
        
        internal static string SparseSequenceConstructorIndexOutofRange {
            get {
                return ResourceManager.GetString("SparseSequenceConstructorIndexOutofRange", resourceCulture);
            }
        }
        
        internal static string ExpectedEveryRemappedColKeyToBeInOriginalMatrix {
            get {
                return ResourceManager.GetString("ExpectedEveryRemappedColKeyToBeInOriginalMatrix", resourceCulture);
            }
        }
        
        internal static string NCBIQBLAST_NAME {
            get {
                return ResourceManager.GetString("NCBIQBLAST_NAME", resourceCulture);
            }
        }
        
        internal static string InvalidOptionalField {
            get {
                return ResourceManager.GetString("InvalidOptionalField", resourceCulture);
            }
        }
        
        internal static string ToStringFormat {
            get {
                return ResourceManager.GetString("ToStringFormat", resourceCulture);
            }
        }
        
        internal static string FASTQ_FILEEXTENSION {
            get {
                return ResourceManager.GetString("FASTQ_FILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string MsgReverseComplementOverlapItems {
            get {
                return ResourceManager.GetString("MsgReverseComplementOverlapItems", resourceCulture);
            }
        }
        
        internal static string MatrixSpecialValueUseError {
            get {
                return ResourceManager.GetString("MatrixSpecialValueUseError", resourceCulture);
            }
        }
        
        internal static string DeltaAlignmentToStringFormat {
            get {
                return ResourceManager.GetString("DeltaAlignmentToStringFormat", resourceCulture);
            }
        }
        
        internal static string KmerLengthEven {
            get {
                return ResourceManager.GetString("KmerLengthEven", resourceCulture);
            }
        }
        
        internal static string NEWICK_FORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("NEWICK_FORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionUnknownParameterFound {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionUnknownParameterFound", resourceCulture);
            }
        }
        
        internal static string BAM_INDEXFILEEXTENSION {
            get {
                return ResourceManager.GetString("BAM_INDEXFILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string FASTAFORMATTER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FASTAFORMATTER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string PAIRWISE_DESCRIPTION {
            get {
                return ResourceManager.GetString("PAIRWISE_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string FIELDPARSER_FILEEXTENSION {
            get {
                return ResourceManager.GetString("FIELDPARSER_FILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string InvalidEncodedQualityScoreFound {
            get {
                return ResourceManager.GetString("InvalidEncodedQualityScoreFound", resourceCulture);
            }
        }
        
        internal static string ParserIncorrectAlphabet {
            get {
                return ResourceManager.GetString("ParserIncorrectAlphabet", resourceCulture);
            }
        }
        
        internal static string SequenceStatisticsToStringFormat {
            get {
                return ResourceManager.GetString("SequenceStatisticsToStringFormat", resourceCulture);
            }
        }
        
        internal static string FASTAPARSER_DESCRIPTION {
            get {
                return ResourceManager.GetString("FASTAPARSER_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string ParserInvalidReferenceField {
            get {
                return ResourceManager.GetString("ParserInvalidReferenceField", resourceCulture);
            }
        }
        
        internal static string SERVICE_HANDLER_ASSEMBLY {
            get {
                return ResourceManager.GetString("SERVICE_HANDLER_ASSEMBLY", resourceCulture);
            }
        }
        
        internal static string PairwiseAlignerWrongArgumentCount {
            get {
                return ResourceManager.GetString("PairwiseAlignerWrongArgumentCount", resourceCulture);
            }
        }
        
        internal static string ErrorConvertingDoubleToNucleotide {
            get {
                return ResourceManager.GetString("ErrorConvertingDoubleToNucleotide", resourceCulture);
            }
        }
        
        internal static string ExpectedMatrixViewRowKeysToBeSubsetOfParentMatrix {
            get {
                return ResourceManager.GetString("ExpectedMatrixViewRowKeysToBeSubsetOfParentMatrix", resourceCulture);
            }
        }
        
        internal static string ParameterNamePosition {
            get {
                return ResourceManager.GetString("ParameterNamePosition", resourceCulture);
            }
        }
        
        internal static string GAP_COST_DESCRIPTION {
            get {
                return ResourceManager.GetString("GAP_COST_DESCRIPTION", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionRepeatedParameterFound {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionRepeatedParameterFound", resourceCulture);
            }
        }
        
        internal static string CmdLineParserExceptionSyntaxError {
            get {
                return ResourceManager.GetString("CmdLineParserExceptionSyntaxError", resourceCulture);
            }
        }
        
        internal static string ParserReferenceError {
            get {
                return ResourceManager.GetString("ParserReferenceError", resourceCulture);
            }
        }
        
        internal static string SIMPLE_SNP_FILEEXTENSION {
            get {
                return ResourceManager.GetString("SIMPLE_SNP_FILEEXTENSION", resourceCulture);
            }
        }
        
        internal static string ARGUMENT_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("ARGUMENT_OUT_OF_RANGE", resourceCulture);
            }
        }
    }
}
